spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
#    url: jdbc:h2:mem:articledb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms

jwt:
  secret: ${JWT_SECRET:your-secret-key-must-be-at-least-256-bits}
  access-token-validity-ms: 3600000 # 1시간
  refresh-token-validity-ms: 1209600000 # 2주

logging:
  level:
    com.yourssu.application: DEBUG
    org.springframework.security: DEBUG